# Generated by Django 6.1.1 on 2026-10-02 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('manager', '0002_project_task_project_team_project_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Група дозволів, яка буде автоматично надана працівникам цієї посади.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='auth.group'),
        ),
    ]
