# Generated by Django 6.1.1 on 2026-10-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_position_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Blocker', 'Blocker'), ('Critical', 'Critical'), ('Major', 'Major'), ('Minor', 'Minor'), ('Trivial', 'Trivial')], default='Major', max_length=20),
        ),
    ]
