# Generated by Django 6.1.1 on 2026-10-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В роботі'), ('review', "На рев'ю"), ('approved', 'Заапрувлено'), ('rejected', 'Відхилено')], default='in_progress', max_length=20),
        ),
    ]
