# Generated by Django 6.1.1 on 2026-10-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='task_types',
            field=models.ManyToManyField(blank=True, help_text='Типи завдань, на яких спеціалізується ця команда.', related_name='teams', to='manager.tasktype'),
        ),
    ]
